### ISSUE TITLE
Countdown command

### ISSUE THREAD

**Issue by DwarfWoot** [ManicJamie/HornetBot#6]
A command such as `;countdown` (aliases `;c`, `;count`, `;cd`) that outputs a message that is `<t:unixTimestamp:R>` where `unixTimestamp` is the current timestamp + 30 seconds (If you wanted to add an argument, you could allow the user to input a number and then it would be + number seconds instead)

Reason: realized that discord will display the countdown live if it's less than a minute, which I think would be convenient for starting races
(if you aliases aren't supported, then probably `count` or `cd` are better names)

**Comment by DwarfWoot** [comment]
(I cannot find a way to tag this as "Suggestion")

**Comment by ManicJamie** [comment]
Good addition, added [7bf0141](https://github.com/ManicJamie/HornetBot/commit/7bf0141baecfc024dfaeba356144608aa236006e)
